name: VM-github mapper
on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: 'Set Machine type to'
        default: default
        required: true
        type: choice
        options:
          - default
          - standard-CPU
          - standard-GPU

jobs:
  vm-github-mapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Get the git username
    - name: 'Get the Github username'
      id: get_username
      run: |
        username=${{github.actor }}
        echo ${{ github.actor }}
        profile_name=${username%-code}
        echo "profile_name=$profile_name" >> "$GITHUB_OUTPUT"

      # Get VM instance name
    - name: 'Get the VM instance name'
      id: get_vm_name
      run: |
        profile_name=${{ steps.get_username.outputs.profile_name }}
        vm_instance="labvm-alephone labvm-alephzero labvm-banothh labvm-felixte labvm-hitzp labvm-ponnampal"
        for user in $vm_instance; do
          substring=${user#*-}
          echo $substring
          echo $profile_name
            found=false
            if [[ $substring == "banothh" ]]; then
             echo "vm_name=$vm_instance" >> "$GITHUB_OUTPUT"
             found=true
             echo "It's there!"
            break
            elif [[ "$found" == "true" ]]; then
            echo "ccc"
          else
          echo "something else"
           fi
        done
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
        echo "${{ steps.matrix.outputs.value }}"
    steps:
      - id: matrix
        run: |
          echo "value=[\"a\", \"b\", \"c\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
      needs: [ setup ]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          value: ${{fromJSON(needs.setup.outputs.matrix)}}
      steps:
        - run: |
            echo "${{ matrix.value }}"
  update_to_standed:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "profile_name=${{ needs.get_username.outputs.profile_name }}"
              echo $profile_name
            if: inputs.machine_type == 'standard-GPU'
            runs-on: ubuntu-latest
            steps:
            - name: Update VM
              run: |
                profile_data=${{fromJSON(needs.vm-github-mapper.outputs.vm_matrix)}}
                echo "profile_data"