name: VM-github mapper
on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: 'Set Machine type to'
        default: default
        required: true
        type: choice
        options:
          - default
          - standard-CPU
          - standard-GPU
jobs:
  vm-github-mapper:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    # Get the git username
    - name: 'Get the Github username'
      run: |
        username=${{github.actor }}
        echo ${{ github.actor }}
        profile_name="${username%-code}"