name: VM-github mapper
on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: 'Set Machine type to'
        default: default
        required: true
        type: choice
        options:
          - default
          - standard-CPU
          - standard-GPU
jobs:
  vm-github-mapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Get the git username
    - name: 'Get the Github username'
      run: |
        username=${{github.actor }}
        echo ${{ github.actor }}
        profile_name=${username%-code}
        echo $profile_name
    # Get VM instance name
    - name: 'Get the VM instance name'
      run: |
        vm_instance="labvm-alephone labvm-alephzero labvm-banothh labvm-felixte labvm-hitzp labvm-ponnampal"
        for user in $vm_instance; do
          substring=${user#*-}
          echo $substring
            if [[ $substring == $profile_name ]]; then
             echo "It's there!"
            else
            echo " User not available"
           fi
        done
