name: VM-github mapper
on:
  workflow_dispatch:
    inputs:
      machine_type:
        description: 'Set Machine type to'
        default: default
        required: true
        type: choice
        options:
          - default
          - standard-CPU
          - standard-GPU

jobs:
  vm-github-mapper:
    runs-on: ubuntu-latest
    outputs:
      profile_name: ${{ steps.get_username.outputs.profile_name }}
      vm_name: ${{ steps.get_vm_name.outputs.vm_name }}
    steps:
    - uses: actions/checkout@v4
    # Get the git username
    - name: 'Get the Github username'
      id: get_username
      run: |
        username=${{github.actor }}
        echo ${{ github.actor }}
        profile_name=${username%-code}
        echo "profile_name=$profile_name" >> "$GITHUB_OUTPUT"
        echo "::set-output name=profile_name::$profile_name"

      # Get VM instance name
    - name: 'Get the VM instance name'
      id: get_vm_name
      run: |
        profile_name=${{ steps.get_username.outputs.profile_name }}
        vm_instance="labvm-alephone labvm-alephzero labvm-banothh labvm-felixte labvm-hitzp labvm-ponnampal"
        for user in $vm_instance; do
          substring=${user#*-}
          echo $substring
          echo $profile_name
            found=false
            if [[ $substring == "banothh" ]]; then
             echo "vm_name=$vm_instance" >> "$GITHUB_OUTPUT"
             echo "::set-output name=vm_name::$vm_instance"
             found=true
             echo "It's there!"
            break
            elif [[ "$found" == "true" ]]; then
            echo "ccc"
          else
          echo "something else"
           fi
        done
  Update_to_standard_vm:
      if: inputs.machine_type == 'standard-CPU'
      needs: vm-github-mapper
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      # Get the git username
      - name: 'Get the Github username'
        run: |
         echo  "Initial Value: ${{ needs.vm-github-mapper.outputs.vm_name }}"
          echo "profile Value: ${{ needs.vm-github-mapper.outputs.profile_name }}"